Nitrokey/nitrokey-app2

Makefile, dev-requirements.txt, pyproject.toml
* Moves dependencies form `dev-requirements.txt` to `pyproject.toml`.
* Changes `Makefile` to install dependencies with `flit`.
* Update keys in `pyproject.toml`.
=> Changes to migrate to flit

.github/workflows/ci.yaml, Makefile
* Reorganize targets in `Makefile` and use environment variables throughout the file.
* Add Github Actions CI checks for format, import, style, and type checks.
=> Ci pipeline

nitrokeyapp/__main__.py, nitrokeyapp/gui.py
=> Fixes app crashes and hangs on start

nitrokeyapp/update.py
=> lowercase to uppercase

nitrokeyapp/gui.py, nitrokeyapp/nk3_button.py
- the last 4 characters of the uuid are not taken into account when connecting a device
- updates displayed uuid after update
=> considers uuid change of alpha/test versions

nitrokeyapp/__main__.py, nitrokeyapp/gui.py, nitrokeyapp/logger.py, nitrokeyapp/pynitrokey_for_gui.py
- added the logging data to tmp like nitropy
=> added logging to file

.github/workflows/cd-pypi.yaml, ci-scripts/pypi/.pypirc_template
This PR adds a CD pipeline to publish on Pypi.
- Adds pypi configuration file.
- Adds workflow file for Pypi. The workflow requires the `PYPI_TOKEN` variable to contain the secret to publish on Pypi.
=> Cd pipeline pypi

README.md, pyproject.toml
Fixes https://github.com/Nitrokey/nitrokey-app2/issues/55
=> Fix entry point in pyproject.toml

ci-scripts/linux/pyinstaller/nitrokey-app-onedir.spec, ci-scripts/linux/pyinstaller/nitrokey-app-onefile.spec, ci-scripts/windows/pyinstaller/nitrokey-app-onedir.spec, ci-scripts/windows/pyinstaller/nitrokey-app-onefile.spec
=> Add nitrokeyapp metadata during pyinstaller build

nitrokeyapp/secrets_tab/worker.py
This patch extends the credential creation to check for existing credentials with the same name.  If such a credential exists, it would be overwritten.  This is non-intuitive, so we catch this case and show an error instead.
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/104
=> secrets: Don’t overwrite existing credentials

nitrokeyapp/secrets_tab/__init__.py, nitrokeyapp/secrets_tab/ui.py, nitrokeyapp/ui/add_secret_dialog.ui, nitrokeyapp/ui/secrets_tab.ui
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/108
=> secrets: Rename Secrets to Passwords in UI

nitrokeyapp/logger.py
- doesnt delete the file as soon as it is closed anymore
- "If delete is true (the default), the file is deleted as soon as it is closed." (https://docs.python.org/3.9/library/tempfile.html)
=> changed delete to False

nitrokeyapp/gui.py, nitrokeyapp/ui/mainwindow.ui
modified:   nitrokeyapp/gui.py
modified:   nitrokeyapp/ui/mainwindow.ui
=> Remove currently unused icons

nitrokeyapp/gui.py
- removing the unused buttons has broken the home button
- the reset of the gui.py fixes the problem
=> reset gui.py

nitrokeyapp/secrets_tab/worker.py
to request and verify a PIN before a PIN-protected access authorisation is to be deleted.
=> pin request when deleting

nitrokeyapp/secrets_tab/__init__.py, nitrokeyapp/secrets_tab/worker.py
=> uncheck Show Protected Password checkbox if pin entry failed

.github/workflows/ci.yaml
This PR adds a CI pipeline test to check the syntax of the `pyproject.toml` file and its consistency with `poetry.lock` file.
=> Add pyproject.toml check to CI pipeline

nitrokeyapp/welcome_tab.py
This PR changes the request of the last release. 
-> from the VERSION file to a request via api.github
=> fix check for app update

docs/release.md
=> add release docs

nitrokeyapp/ui/overview_tab.ui
change the text on the `btn_update` in the `OverviewTab` from `Update` to `Check for Update`
Closes #84
=> change btn_update

nitrokeyapp/overview_tab/__init__.py, nitrokeyapp/ui/overview_tab.ui
close `more options` when it is open and another Nitrokey is plugged in. 
#225
=> close more options

nitrokeyapp/gui.py, nitrokeyapp/settings_tab/__init__.py, nitrokeyapp/ui/settings_tab.ui
=> settings-rework

nitrokeyapp/overview_tab/__init__.py, nitrokeyapp/overview_tab/worker.py, nitrokeyapp/update.py
=> recognize qubesos

nitrokeyapp/secrets_tab/__init__.py
This PR fixes a typo in a UI element.
=> Fix typo in UI

poetry.lock, pyproject.toml
forgot to remove this after migrating to usb-monitor
=> remove pyudev from deps

nitrokeyapp/settings_tab/__init__.py, nitrokeyapp/settings_tab/worker.py, nitrokeyapp/ui/settings_tab.ui
* clean up codebase
* add "retries" for FIDO2
* make layout and ux consistent within settings
* added some `getInfo` outputs to FIDO2
* fix #263 
* various refactoring work in settings
=> Improve Settings Tab

meta/com.nitrokey.nitrokey-app2.metainfo.xml
=> format flatpak metainfo

nitrokeyapp/device_data.py
`self.status.variant` is exists but is `None`.
Fixes  #273.
=> Fix check for too old firmware.

poetry.lock, pyproject.toml
This PR updates the `nitrokey` dependency.
=> Update nitrokey dependency

docs/release.md
add necessary detail for xml metainfo doc
=> docs: minor in release

.github/workflows/cd-linux.yaml, .github/workflows/cd-windows.yaml
This PR updates the Github Action `softprops/action-gh-release@v1` to version 2.
=> Update release publish action

nitrokeyapp/__main__.py
Set desktop filename to fix window icon under Wayland.
=> fix: rectify window icon under Wayland

meta/com.nitrokey.nitrokey-app2.metainfo.xml
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/333
=> Fix license in metainfo file

nitrokeyapp/update.py
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/315
=> nk3: Only show extra information if set
