Nitrokey/nitrokey-app2

dev-requirements.txt
Execution on Windows crashes with missing `win32api` dependency.
```
Traceback (most recent call last):
File "nitrokey-app2.py", line 5, in <module>
File "nitropyapp\gui.py", line 1035, in main
File "nitropyapp\gui.py", line 150, in __init__
File "nitropyapp\windows_notification.py", line 14, in __init__
ModuleNotFoundError: No module named 'win32api'
```
This PR adds the `pywin32` dependency to fix this issue.
=> Add required dependency for Windows

dev-requirements.txt, nitropyapp/gui.py, nitropyapp/nk3_button.py, nitropyapp/pynitrokey_for_gui.py
This PR upgrade the `pynitrokey` dependency to version `0.4.32`.
It implements a workaround for the NK3 `Uuid` class.
In the past the `uuid()` method on NK3 returned `int`.
With the upgrade of the latest release it returns the `Uuid` class, which only has conversion to `str` implemented.
Opened Nitrokey/pynitrokey#315 to have a conversion method to `int`.
Workaround just calls the `value` attribute of `Uuid` directly.
=> Upgrade pynitrokey dependency to 0.4.32

Makefile, pyproject.toml
This change will make `isort` work by the same rules as `black`. Otherwise they work by different rules, which leads to incompatible changes and a never passing CI.
=> Make isort format compatible with black

.flake8, pyproject.toml
- Set the same maximum line length for isort and flake8.
- Add same configuration for flake8 like on pynitrokey.
=> Improve ci

nitrokeyapp/__main__.py
This PR fixes a broken display of icons in the UI after recent refactor.
The issue was a missing import of `nitrokeyapp.gui_resources`.
It was prior imported to `nitrokeyapp.pin_dialog`.
Now it is imported to `nitrokeyapp.__main__`.
The import of another UI resource `import nitrokeyapp.ui.breeze_resources` from the same file was not moved, as it had no effect.
=> Fix missing icons

README.md
I think you renamed this project but at least the README refers still to "nitropy-app2". I renamed it and now the instructions also work.
=> Rename nitropy-app2 to nitrokey-app2 in README.md

Makefile
* `make check` runs all set up checks and linters
* `make fix` applies `isort` & `black` directly
=> Makefile: add check & fix targets

Makefile
This PR introduces the Makefile target `build-ui`, which automatically creates the `.py` files from the `.ui` files in `nitrokeyapp/ui`.
Currently the change doesn't make it part of the `build` target, because if so the build command complains about untracked or deleted files in the source directory.
Potentially fixes #25
=> Build UI files with Makefile target

pyproject.toml
This updates the mypy dependency to version `>=1,<1.1`. This is in accordance with the configuration of the `pynitrokey` dependency.
=> Bump mypy to minimum version 1.0

pyproject.toml
This PR makes the following changes to the `mypy` configuration:
- Set Python version to `3.9`.
- Include checks for `nitrokeyapp` module and set `disallow_untyped_defs = true`.
- Ignore missing imports for `win32api`, `win32con`, `win32gui`, `pyudev`, `pynitrokey`.
Merge after #32.
=> Mypy configuration

README.md
The build target requires pyrrc5, so we first have to create and activate the virtual environment before running it.
=> Fix manual installation instructions

nitrokeyapp/__main__.py
This patch fixes an issue where the main function would be executed twice.  This is necessary because the entry point is set to `nitrokeyapp.__main__:main`, so first the `__main__` module is imported and then `main` is called explicitly.
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/61
=> Add __name__ check to __main__

nitrokeyapp/update.py, pyproject.toml
This patch updates pynitrokey to v0.4.37.  This release activates type annotations, so we can enable type checking with mypy for pynitrokey.
Depends on:
- https://github.com/Nitrokey/nitrokey-app2/pull/81
=> Enable type checking for pynitrokey

nitrokeyapp/device_view.py, nitrokeyapp/gui.py, nitrokeyapp/overview_tab.py
This patch introduces the `DeviceView` protocol, an abstraction mainly intended for the device tabs but applicable for all widgets  that display device data.
Depends on:
- https://github.com/Nitrokey/nitrokey-app2/pull/81
=> Add abstraction for device tabs

nitrokeyapp/__main__.py, nitrokeyapp/about_dialog.py, nitrokeyapp/error_dialog.py, nitrokeyapp/gui.py, nitrokeyapp/logger.py, nitrokeyapp/ui/aboutdialog.ui
This patch adds a log file for the app in /tmp.  Once the application is closed, the log file is deleted.  If an unexpected error occurs, the user has the option to save the log file so that it can be submitted to us.  The same option is available in the about dialog.
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/74
=> Add log file

nitrokeyapp/secrets_tab/__init__.py, nitrokeyapp/ui/secrets_tab.ui
To make it possible to copy the generated OTP, we show it in a read-only QLineEdit instead of a QLabel.  For consistency, this patch uses a QLineEdit for the algorithm too.
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/105
Ideally, the layouts of the two group boxes would use the same widths, but I’m not sure what’s the best way to achieve that.
=> secrets: Use QLineEdit for OTP

nitrokeyapp/secrets_tab/worker.py
This patch adds a touch prompt when deleting a credential.  While a touch confirmation is not required at the moment, this is unintentional and will be changed in an upcoming firmware release.
See: https://github.com/Nitrokey/trussed-secrets-app/issues/92
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/110
=> secrets: Add touch prompt when deleting credential

nitrokeyapp/add_secret_dialog.py
Previously, the tooltip for the OK button in the Add Secret dialog was not reset if an input error has been resolved.  This patch fixes this oversight.
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/113
=> secrets: Fix error tooltip when adding secret

nitrokeyapp/secrets_tab/__init__.py, nitrokeyapp/ui/secrets_tab.ui
This patch changes the minimum width for all form labels in the secrets tab to the maximum width of all labels.  This makes sure that the labels are properly aligned.
=> secrets: Use same width for labels

Makefile
Adds the `build` and `dist/` directories to the `semi-clean` Makefile target. This is helpful when testing local builds with *pyinstaller*.
=> Build cleanup

.github/workflows/cd-linux.yaml, .github/workflows/cd-pypi.yaml, .github/workflows/cd-windows.yaml
This PR changes the event triggers of the CD pipelines to respond to `prereleased` and `released`, instead of `published` and `unpublished`. There is an exception for the Pypi pipeline to only get triggered on `released` event. Reason for this is to not push test releases to Pypi, which could end up in a production environment.
Fixes #119
=> Change event triggers from un/published to pre/released

pyproject.toml
This patch updates pynitrokey to 0.4.40 and mypy to 1.4.
pynitrokey 0.4.39 updated the sdsk dependency which fixes a build issue on some systems.  0.4.40 also fixed the “generator did not stop after throw” issue that has also been reported for the app.
mypy 1.4 fixes an occasional type checking error that had to be fixed by removing the cache.
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/144
=> Bump pynitrokey, mypy

nitrokeyapp/secrets_tab/__init__.py, nitrokeyapp/ui/secrets_tab.ui
add COPY TO CLIPBOARD Button for ONE TIME PASSWORD
=> Copy to clipboard

.github/workflows/cd-pypi.yaml, Makefile
This PR includes the dynamically created `*.py` files in `nitrokeyapp/ui` into the wheel and source archive uploaded to Pypi.
- The build command of *flit* only includes files checked in to the VCS. The default is changed with option `--no-use-vcs`.
- The *Pypi* pipeline was executing the command without the above option as well. This change makes it use the Makefile `build` target.
Fixes #162
=> Fix missing UI resource files

.github/workflows/cd-pypi.yaml
This PR adds the `libglib2.0-0` package to the CD pipeline for Pypi. Change is necessary to prevent the pipeline from failing due to a missing dependency for compiling Qt5 UI files.
=> Add libglib2.0 for libgthread

nitrokeyapp/secrets_tab/__init__.py
=> fix timeout UI OTP

nitrokeyapp/gui.py, nitrokeyapp/overview_tab.py
During the update process, the gui is now in a waiting state. 
It is no longer possible to click on anything else in the app (except the help). 
The cursor also shows the waiting status.
Fix: #160
=> During the update process, the gui is busy

Makefile
This PR disables the use of keyrings for Poetry.
On certain systems *Poetry* produces unlock requests for the keyring, even though the access is not required.
This change configures the `Null` keyring, which makes the requests stop.
An unlocked keyring is not required for our environment.
=> Disable the use of keyrings for Poetry

pyproject.toml
This PR sets the required version for the build system to `>=1.3.2`.
The background for this change is that *poetry-core* supports Python 3.11 only from version `1.3.2` on.
See related release notes [here](https://python-poetry.org/history/#poetry-core-132httpsgithubcompython-poetrypoetry-corereleasestag132).
=> Set required build system version to >=1.3.2

ci-scripts/linux/pyinstaller/nitrokey-app-onedir.spec, ci-scripts/windows/pyinstaller/nitrokey-app-onedir.spec, poetry.lock, pyproject.toml
This PR upgrades the *pyinstaller* dependency and reverts the configuration to the old behavior of collecting the dependencies in the same directory as the binary.
After this change the supported Python version is raised to `3.12`.
Fixes [CVE-2023-49797](https://github.com/advisories/GHSA-9w2p-rh8c-v9g5).
=> Upgrade pyinstaller

.github/workflows/cd-pypi.yaml
This PR changes the PyPI repository URL.
In the past the repository URL `https://upload.pypi.org/legacy/` was used. During a change of the build system this was mistakenly changed to `https://pypi.org/legacy/`, which causes the PyPI publishing to fail.
This change also makes the URL being passed as environment variable of the workflow job.
=> Change PyPI repository url

nitrokeyapp/secrets_tab/__init__.py
This catches some user-interactions which could lead to the "save" button being not correctly activated.
The following error case should not appear anymore:
* edit a credential with OTP already set
* click on "edit" in the OTP row - "save" was still active (should not be the case anymore with this PR)
=> pw-manager: properly handle save-button activation during edit

.github/workflows/cd-linux.yaml, .github/workflows/cd-pypi.yaml, .github/workflows/cd-windows.yaml, .github/workflows/ci.yaml
This PR updates the Github Actions `actions/checkout`, `actions/download-artifact`, and `actions/upload-artifact` from version 3 to 4. This is required because of the deprecation of NodeJS 16, used by the version 3 of these actions. It also removes the packaging of binary artifacts in an archive.
=> Update used Github Actions in CICD pipelines

nitrokeyapp/common_ui.py, nitrokeyapp/device_data.py, nitrokeyapp/device_manager.py, nitrokeyapp/device_view.py, nitrokeyapp/gui.py, nitrokeyapp/information_box.py, nitrokeyapp/nk3_button.py, nitrokeyapp/overview_tab/__init__.py, nitrokeyapp/overview_tab/worker.py, nitrokeyapp/progress_box.py, nitrokeyapp/prompt_box.py, nitrokeyapp/secrets_tab/__init__.py, nitrokeyapp/secrets_tab/worker.py, nitrokeyapp/touch.py, nitrokeyapp/ui/mainwindow.ui, nitrokeyapp/ui/overview_tab.ui, nitrokeyapp/update.py, nitrokeyapp/worker.py, pyproject.toml
* migrate current overview and updating to worker concept, thus into a thread
* added `PromptBox` for a app-wide confirmation dialog
* added `ProgressBox` for a app-wide progress bar
* create `OverviewWorker` infrastructure
* move `TouchDialog` and `TouchIndicator` into `touch.py`
* add `DeviceManager` and enable support for Nitrokey 3s in bootloader mode
* updating Nitrokey 3s now possible from bootloader or from within application firmware
* various smaller layout fixes
=> Overview refactoring

nitrokeyapp/secrets_tab/__init__.py
Check the length of the comment if it is too long to save, the `Save` button is disabled and the `info_box` displays _"Comment is too long"_.
Closes #223
=> check length of comment before saving

nitrokeyapp/progress_box.py
previously if the time between initializing (`show`) the progress bar and the first `update` was > 7secs (the auto-hide timeout) the progress bar would be updated without being shown.
This case might happen while updating nk3am devices
=> always call show on progress-bar on update

Makefile
This PR removes the Makefile variables `UI_FILES_PATH` and `UI_FILES`. They're not used anymore, since we migrated to uncompiled UI files.
=> Remove unused makefile variables

ci-scripts/linux/rpm/nitrokey-app2.spec
the copr build pipeline is confused by the 
`BuildArch:		x86_64`
Line removing it fixes the Problem and successful builds the package
=> fix copr build

.github/workflows/cd-windows.yaml
This PR appends the string `_unsigned` to the published Windows executable and installer files. During manual signing process we remove the appended string again. This way it is clear which artifacts are signed.
Fixes #221
=> Append unsigned name to published windows binaries

nitrokeyapp/gui.py
This PR makes sure that all QThread instances are quit before the application exits. Eventually we need to evaluate if we need to await some of them and how this works together with the `TERM` signal.
Currently, this avoids that users see an `Application quit unexpectedly` or similar error messages.
Fixes #215
=> Quit all qthreads on close event

nitrokeyapp/__init__.py, nitrokeyapp/device_data.py, nitrokeyapp/logger.py, nitrokeyapp/overview_tab/__init__.py, nitrokeyapp/secrets_tab/data.py, nitrokeyapp/secrets_tab/worker.py, nitrokeyapp/settings_tab/__init__.py, nitrokeyapp/settings_tab/worker.py, nitrokeyapp/update.py, nitrokeyapp/welcome_tab.py, poetry.lock, pyproject.toml
This patch replaces the pynitrokey dependency with the [Nitrokey Python SDK](https://github.com/Nitrokey/nitrokey-sdk-py).  For FIDO2 interactions, the fido2 library can be used directly.  `Retries` is so simple that it can be copied from pynitrokey.
=> Use Nitrokey Python SDK

Makefile
Poetry fails to install dependencies on KDE Plasma 6 due to some missing D-Bus endpoint. Looks like somebody ran into this issue before but the feature wasn't disabled properly in the Makefile.
The error I ran into looks like this:
```
export PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring
poetry env use python3
Creating virtualenv nitrokeyapp-0E2Fz7gS-py3.10 in ~/.cache/pypoetry/virtualenvs
Using virtualenv: ~/.cache/pypoetry/virtualenvs/nitrokeyapp-0E2Fz7gS-py3.10
poetry install --sync --without=deploy
Installing dependencies from lock file
Package operations: 41 installs, 1 update, 0 removals
- Installing pycparser (2.22)
- Installing shiboken6 (6.7.2): Failed
DBusErrorResponse
[org.freedesktop.DBus.Error.UnknownObject] ("No such object path '/org/freedesktop/secrets/prompt/p1'",) …
```
=> Properly disable the Poetry SecretService/Keyring feature

nitrokeyapp/device_data.py, nitrokeyapp/gui.py, nitrokeyapp/overview_tab/__init__.py
Introduce `DeviceData.is_too_old` to test the Nitrokey 3 for important features being used. To be extended with whatever further identifies functionality which is used in `nkapp2`.
If the firmware is classified as too old:
* disable Settings + Passwords tab
* inform the user about the situation in Overview tab
* still allow "update" to be run
=> recognize and handle too old firmwares; fixes #273

.github/workflows/cd-windows.yaml, ci-scripts/linux/pyinstaller/nitrokey-app-onedir.spec, ci-scripts/linux/pyinstaller/nitrokey-app-onefile.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onedir_arm64.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onedir_intel64.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onefile_arm64.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onefile_intel64.spec, ci-scripts/windows/pyinstaller/nitrokey-app-onedir.spec, ci-scripts/windows/pyinstaller/nitrokey-app-onefile.spec
This PR change the build dependencies for the CD pipeline to take the recent changes from `pynitrokey` to `nitrokey` dependency into account. It also remove a not needed invocation of `make build-ui` in the Windows pipeline.
=> Adapt build dependencies

.github/workflows/ci.yaml, meta/com.nitrokey.nitrokey-app2.metainfo.xml
CI still fails because it cannot reach nitrokey.com (403).  Let’s see if that is a temporary or persistent problem.
=> Lint and fix appstream metadata

.github/workflows/ci.yaml
This PR adds two checks to the CI, which compare the package version from `pyproject.toml` with the versions in `nitrokey-app2.spec` and `com.nitrokey.nitrokey-app2.metainfo.xml`.
=> Check version accordance

ci-scripts/linux/rpm/nitrokey-app2.spec
This PR updates the RPM specification file to take into account the new build process.
Detailed changes:
- Remove build with _pyinstaller_ and the associated build requirements.
- Introduce new Python dependencies which are partly maintained by Nitrokey.
- Make use of more RPM macros.
=> Update RPM specification file

pyproject.toml
This PR removes unused mypy overrides in `pyproject.toml`.
Detailed mypy override changes:
- Remove `pyudev`. Dependency remove in f1d39e2aa74f0cdfc32298ab3ddd839cf1270fae.
- Remove `ruamel`. Dependency of `pynitrokey`.
- Remove `tlv8`. Dependency of `nitrokey` (`nitrokey-sdk-py`).
- Remove `qt_material`. Dependency removed in e59caa26ec75708b709142a9c17c9abda6a3606b.
=> Remove unused mypy overrides

ci-scripts/linux/pyinstaller/nitrokey-app-onedir.spec, ci-scripts/linux/pyinstaller/nitrokey-app-onefile.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onedir_arm64.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onedir_intel64.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onefile_arm64.spec, ci-scripts/macos/pyinstaller/nitrokey-app-onefile_intel64.spec, ci-scripts/windows/pyinstaller/nitrokey-app-onedir.spec, ci-scripts/windows/pyinstaller/nitrokey-app-onefile.spec
This PR removes the metadata copying for the `ecdsa` dependency from the *pyinstaller* build.
=> Remove `ecdsa` dependency from pyinstaller build

poetry.lock
This patch updates the locked usb-monitor version to v1.23.  This release should include a fix for the crash on Windows if a printer is connected.
See also:
- https://github.com/Eric-Canas/USBMonitor/issues/6
- https://github.com/Eric-Canas/USBMonitor/commit/f7ea7992fd636a83bd497f2c41ae43a79dc34e39
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/288
=> Update usb-monitor to v1.23

.gitattributes
Per default, GitHub treats poetry.lock as a generated file and hides its diff in pull requests.  That can be confusing if the locked dependency version changes without a corresponding change in pyproject.toml.  This patch marks poetry.lock as not auto-generated so that the full diff is shown.
See also: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
=> Enable full diff for poetry.lock file

meta/com.nitrokey.nitrokey-app2.metainfo.xml
only the `developer` warning so far, partly fixes #311
=> fix flathub metadata-lint warning

.github/workflows/cd-pypi.yaml
Example run: https://github.com/Nitrokey/nitrokey-app2/actions/runs/16495558157
=> ci: Use Trusted Publishing for PyPI releases

nitrokeyapp/device_data.py, nitrokeyapp/overview_tab/__init__.py, nitrokeyapp/overview_tab/worker.py, nitrokeyapp/update.py, poetry.lock, pyproject.toml
This PR updates nitrokey-sdk-py to v0.4, checks the device status after the update and improves the way errors are displayed during firmware updates.
For example, trying to update to an older version now leads to this message:
And the potential EFS error after updating to v1.8.2 looks like this:
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/296
Fixes: https://github.com/Nitrokey/nitrokey-app2/issues/339
=> Update nitrokey-sdk-py to v0.4

README.md, docs/readme.md
This patch updates the readme to refer to docs.nitrokey.com for user documentation.  Basic developer documentation is added to the docs directory.
=> Refer to docs.nitrokey.com for user documentation

.github/workflows/cd-linux.yaml
This makes sure that the produced Linux binary also works with older glibc versions.
=> ci: Use Debian Bookworm for Linux CD
